<?php

namespace AppBundle\Repository;

/**
 * DoctorOfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorOfficeRepository extends \Doctrine\ORM\EntityRepository
{
}
