<?php

namespace AppBundle\Repository;

/**
 * doctorOfficeComplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class doctorOfficeComplementRepository extends \Doctrine\ORM\EntityRepository
{
}
