fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
app_complement:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /