complement_index:
    path:     /
    defaults: { _controller: "AppBundle:Complement:index" }
    methods:  GET

complement_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Complement:show" }
    methods:  GET

complement_new:
    path:     /new
    defaults: { _controller: "AppBundle:Complement:new" }
    methods:  [GET, POST]

complement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Complement:edit" }
    methods:  [GET, POST]

complement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Complement:delete" }
    methods:  DELETE
