AppBundle\Entity\Complement:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ComplementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 30
        civility:
            type: string
            length: 10
        birthname:
            type: string
            length: 30
            nullable: true
        birthdate:
            type: date
            nullable: true
        phone1:
            type: integer
            nullable: false
        phone2:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }