AppBundle\Entity\Complement:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ComplementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        civility:
            type: string
            length: 3
        firstname:
            type: string
            length: 30
        name:
            type: string
            length: 30
        birthname:
            type: string
            length: 30
            nullable: true
        birthdate:
            type: date
            nullable: true
        phone1:
            type: integer
            nullable: true
        phone2:
            type: integer
            nullable: true
            
    oneToOne:
        user:
            targetEntity: UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id


    lifecycleCallbacks: {  }