AppBundle\Entity\DoctorOffice:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DoctorOfficeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        address:
            type: string
            length: 255
        zipcode:
            type: integer
        city:
            type: string
            length: '70'
    lifecycleCallbacks: {  }
